services:
  postgres:
    image: postgres:16.3
    container_name: my_postgres_container
    environment:
      POSTGRES_USER: e-commerce
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: e-commerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3.13.7-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: e-commerce
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
volumes:
  postgres_data: {}
